MDScreen:
    name: 'test'
    md_bg_color: 41/255, 34/255, 34/255, 1
    on_enter: app.load_products()
    image1: ""
    RecycleView:
        viewclass: "OwnWidget" 
        data: app.data
        RecycleBoxLayout:
            default_size: None, dp(300)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            orientation: 'vertical'
            spacing: dp(20)
<OwnWidget@BoxLayout>:
    orientation: 'vertical'
    text: ''
    source:'' 
    MDIconButton:
        icon: 'arrow-left'
        icon_color: 'white'
        theme_icon_color: 'Custom'
        pos_hint: {'center_x':0.3, 'center_y': 0.1}  
        size_hint_x: 0.3
        height: dp(40)
        on_press:
            app.print_source(product.source)
            app.reload_datas()
    AsyncImage:
        id: product
        source: root.source

    